export const paperContent = [
    {
        subjectId: "1",
        subjectTitle: "1Artificial Intelligence",
        subjectExcerpt: [
            "React is an open-source JavaScript library developed by Facebook for building user interfaces, particularly single-page applications where a dynamic and high-performing user experience is crucial.",
            "It focuses on the view layer of the MVC (Model-View-Controller) architecture and enables developers to create reusable UI components. "
        ],
        subjectCardImage: "/images/paperImage/AI1.jpg",
        subjectPageImage: "/images/paperImage/AI2.jpg",
        subjectPageIntro: ["React is a framework that employs Webpack to automatically compile React, JSX, and ES6 code while handling CSS file prefixes. React is a JavaScript-based UI development library. Although React is a library rather than a language, it is widely used in web development. The library first appeared in May 2013 and is now one of the most commonly used frontend libraries for web development.", "React offers various extensions for entire application architectural support, such as Flux and React Native, beyond mere UI.",],
        chapters: [
            {
                id: "1",
                type: "blog",
                createdAt: "July 03, 2024",
                thumbnailImage: "/images/blogImage/React-image.jpg",
                excerpt: ["Designed to encapsulate and manage the user interface (UI) in a modular, reusable manner.", "React components are the fundamental building blocks of React applications, designed to encapsulate and manage the user interface (UI) in a modular, reusable manner. This blog explores the core concepts behind React components, their importance, and best practices for their implementation."],
                title: "1.1Artificial intelligence and its scope in different areas with special reference to the field of education",
                body: {
                    writers: ["John Doe"],
                    address: "Department of Education, Rama PG College, University of Lucknow, Chinhat, Lucknow, Uttar Pradesh, India",
                    abstract: ["In the future, intelligent machines will replace or enhance human capabilities in many areas. Artificial intelligence is the intelligence exhibited by machines or software. It is the subfield of computer science. Artificial intelligence is becoming a popular field in computer science as it has enhanced the human life in many areas. Artificial intelligence in the last two decades has greatly improved performance of the manufacturing, service sector and so in the field of education. Study in the field of artificial intelligence has given rise to the rapidly growing technology known as expert system. Application areas of artificial intelligence is heaving a huge impact on various fields of life as expert system is widely used in these days to solve the complex problems in various areas as education, engineering, business, medicine, weather forecasting etc. The areas employing the technology of artificial intelligence have seen an increase in the quality and efficiency. This paper gives an overview of this technology and the scope of artificial intelligence in different areas with special reference to the use of this technology in the field of education along with its meaning, searching techniques, inventions and future.",],
                    keywords: ["artificial intelligence (AI)", "artificial neurons (neural computer networks)", "expert system", "heuristic", "searching techniques",],
                    contents: [
                        {
                            secTitle: "Introduction",
                            secContent: ["It is claimed that artificial intelligence is playing an increasing role in the research of educational technology, management sciences and operational research areas. Intelligence is commonly considered as the ability to collect knowledge to solve complex problems. In the near future intelligent machines will replace human capabilities in many areas. Artificial intelligence is the study of intelligent machines and software that can reason, learn, gather knowledge, communicate, manipulate and perceive the objects. John McCarthy coined the term in 1956 as branch of computer science concerned with making computers behave like humans. It is the study of the computation that makes it possible to perceive reason and act. Artificial intelligence is different from Psychology because it emphasis on computation and is different from computer science because of its emphasis on perception, reasoning and action.", "It makes machines smarter and more useful. It works with the help of artificial neurons (artificial neural network) and scientific theorems (if then statements and logics). AI technologies have matured to the point in offering real practical benefits in many of their applications. Major artificial intelligence areas are Expert systems, Intelligent computer aided instructions, Natural language processing, Speech understanding, Robotics and sensory systems, Computer vision and scene recognition, Neural computing. From these expert system is a rapidly growing technology which is heaving a huge impact on various field of life. The various techniques applied in artificial intelligence are Neural network, Fuzzy logic, Evolutionary computing, Computer aided instructions and Hybrid artificial intelligence", "Artificial intelligence has the advantages over the natural intelligence as it is more permanent, consistent, less expensive, has the ease of duplication and dissemination, can be documented and can perform certain tasks much faster and better than human. Thus is effective in educational technology to make the teaching learning process more effective and concrete with the help of various artificial intelligence teaching techniques."],
                            secImage: "/images/paperImage/image1.jpg",
                            secImageCaption: "Papers published on different AI techniques quarterly",
                        },
                        {
                            secTitle: "Meaning of artificial intelligence",
                            secContent: ["Artificial intelligence is the combination of two words artificial + intelligence. Where artificial means ‘not real’ or ‘natural’ and by intelligence means ‘the ability to reason, to trigger new thoughts, to perceive and learn’.It is effective in educational technology to make the teaching learning process more effective and concrete with the help of various artificial intelligence teaching techniques. Artificial intelligence can be defined that area of computer science that mainly focus on the making on such kind of intelligent machines that work and give reactions same like human beings. It is combination of many activities which includes for designing the artificial in computers that are like-recognizing the speech, learning, planning and solving the problem. When any system adapts itself according to situation in any environment is called intelligent.", "In other words, it can be defined as programming such machines which can think and act with some level of human intelligence is known as artificial intelligence. Artificial intelligence can be defined as efficiently use of limited resources. So artificial intelligence can be defined as making computer programs to solve complex problems same like as human solve the problems. So it is also divided into two parts one is to solving complex problems by the machine and second is same like human beings. The term artificial intelligence is also used to describe a property of machines or programs: the intelligence that the system demonstrates. Artificial intelligence is combination of science and engineering for making the machines which behaves in intelligent manner. In it many fields are combined like philosophy, psychology and computer science."],
                            secImage: "/images/paperImage/image2.jpg",
                            secImageCaption: " Working of a search engine",

                        },
                        {
                            secTitle: "Scope of artificial intelligence in different areas",
                            secContent: [],
                            subSection: [
                                {
                                    subSectionTitle: "In the field of education",
                                    subSectionContent: [],
                                    subSubSection: [{
                                        subsubSectionTitle: "Artificial intelligence can automate basic activities in education, like grading",
                                        subsubSectionContent: ["While AI may not ever be able to truly replace human grading, it’s getting pretty close. It’s now possible for teachers to automate grading for nearly all kinds of multiple choice and fill-in-the-blank testing and automated grading of student writing may not be far behind. Today, essay-grading software is still in its infancy and not quite up to par, yet it in college, grading homework and tests for large lecture courses can be tedious work, even when TAs split it between them. Even in lower grades, teachers often find that grading takes up a significant amount of time, time that could be used to interact with students, prepare for class, or work on professional development."],
                                    },
                                    {
                                        subsubSectionTitle: "Educational software can be adapted to student needs",
                                        subsubSectionContent: ["From kindergarten to graduate school, one of the key ways artificial intelligence will impact education is through the application of greater levels of individualized learning. Some of this is already happening through growing numbers of adaptive learning programs, games, and software. These systems respond to the needs of the student, putting greater emphasis on certain topics, repeating things that students haven’t mastered, and generally helping students to work at their own pace, whatever that may be. This kind of custom tailored education could be a machine-assisted solution to helping students at different levels work together in one classroom, with teachers facilitating the learning and offering help and support when needed.", "Adaptive learning has already had a huge impact on education across the nation (especially through programs like Khan Academy), and as AI advances in the coming decades adaptive programs like these will likely only improve and expand."],
                                    },]
                                },
                                {
                                    subSectionTitle: "Language understanding",
                                    subSectionContent: ["Teachers may not always be aware of gaps in their lectures and educational materials that can leave students confused about certain concepts. Artificial intelligence offers a way to solve that problem. Coursera, a massive open online course provider, is already putting this into practice. When a large number  of students are found to submit the wrong answer to a homework assignment, the system alerts the teacher and gives future students a customized message that offers hints to the correct answer. This type of system helps to fill in the gaps in explanation that can occur in courses, and helps to ensure that all students are building the same conceptual foundation. Rather than waiting to hear back from the professor, students get immediate feedback that helps them to understand a concept and remember how to do it correctly the next time around.", "The ability to 'understand' and respond to the natural language. To translate from spoken language to a written form and to translate from one natural language to another natural language."],
                                    subSectionImage: "/images/paperImage/image3.jpg",
                                    subSectionImageCaption: "Working of a search engine",
                                },]
                        },
                        {
                            secTitle: "Searching techniques in artificial intelligence",
                            secContent: ["In AI for finding the solution of problem searching has to be done because solution is not known in advance. For it AI programs are developed which do the searching process for solution because solution steps are not known before hand and have to be found out. For doing searching following steps are required. So we can say that searching is a process which transform initial state to goal state."],
                        },
                        {
                            secTitle: "Conclusion",
                            secContent: ["The field of artificial intelligence gives the ability to the machines to think analytically, using concepts. Tremendous contribution to the various areas has been made by the Artificial Intelligence techniques from the last 2 decades. Artificial Intelligence will continue to play an increasingly important role in the various fields. This paper is based on the concept of artificial intelligence, scope of artificial intelligence in different areas with special to “the field of education”. As all know artificial intelligence is intelligence behavior of machines which is given by the professional. As you all know artificial intelligence have simplified our life in every aspect it can be article writing or game playing or taking any important decision. In any machine many experts mind can be combined which is more powerful than a single expert mind.", "Many labors work can be done by a single machine and good thing of it is that it never tired. Now such types of robots are going to make which have emotions it will finish the loneliness of the person. But it has another aspect that is can be dangers for us. If we become completely dependent on that machines than it can ruin our life as we do not do any work ourselves and got lazy. And another is that it cannot give the feeling like human. So machines should be used only where there those are actually required."],

                        },
                    ],
                    reference: ["Ramesh N, Kambhampati C, Monson JRT, Drew PJ. Artificial intelligence, 2004.", "Sampada C et al. Adaptive Neuro-Fuzzy Intrusion Detection Systems, Proceedings: International Conference on Information Technology: Coding and Computing ITCC 04, 2004.", "Deepa SN, Aruna Devi B. A survey on intelligence approaches for medical image  Indian Journal of Science and Technology, 2011; 4(11).", "Zadeh L. Fuzzy sets Inf Control, IJET, 2014.", "Joanna Bryson and Jeremy Wyatt. Artificial Intelligence Retrieved from: http://www.cs.bath.ac .uk/~jjb/web/whatisai.html, 1997."]
                }
            },
            {
                id: "2",
                type: "blog",
                createdAt: "July 03, 2024",
                thumbnailImage: "/images/blogImage/React-image.jpg",
                excerpt: ["Designed to encapsulate and manage the user interface (UI) in a modular, reusable manner.", "React components are the fundamental building blocks of React applications, designed to encapsulate and manage the user interface (UI) in a modular, reusable manner. This blog explores the core concepts behind React components, their importance, and best practices for their implementation."],
                title: "1.2Artificial intelligence and its scope in different areas with special reference to the field of education",
                body: {
                    writers: ["John Doe"],
                    address: "Department of Education, Rama PG College, University of Lucknow, Chinhat, Lucknow, Uttar Pradesh, India",
                    abstract: ["In the future, intelligent machines will replace or enhance human capabilities in many areas. Artificial intelligence is the intelligence exhibited by machines or software. It is the subfield of computer science. Artificial intelligence is becoming a popular field in computer science as it has enhanced the human life in many areas. Artificial intelligence in the last two decades has greatly improved performance of the manufacturing, service sector and so in the field of education. Study in the field of artificial intelligence has given rise to the rapidly growing technology known as expert system. Application areas of artificial intelligence is heaving a huge impact on various fields of life as expert system is widely used in these days to solve the complex problems in various areas as education, engineering, business, medicine, weather forecasting etc. The areas employing the technology of artificial intelligence have seen an increase in the quality and efficiency. This paper gives an overview of this technology and the scope of artificial intelligence in different areas with special reference to the use of this technology in the field of education along with its meaning, searching techniques, inventions and future.",],
                    keywords: ["artificial intelligence (AI)", "artificial neurons (neural computer networks)", "expert system", "heuristic", "searching techniques",],
                    contents: [
                        {
                            secTitle: "Introduction",
                            secContent: ["It is claimed that artificial intelligence is playing an increasing role in the research of educational technology, management sciences and operational research areas. Intelligence is commonly considered as the ability to collect knowledge to solve complex problems. In the near future intelligent machines will replace human capabilities in many areas. Artificial intelligence is the study of intelligent machines and software that can reason, learn, gather knowledge, communicate, manipulate and perceive the objects. John McCarthy coined the term in 1956 as branch of computer science concerned with making computers behave like humans. It is the study of the computation that makes it possible to perceive reason and act. Artificial intelligence is different from Psychology because it emphasis on computation and is different from computer science because of its emphasis on perception, reasoning and action.", "It makes machines smarter and more useful. It works with the help of artificial neurons (artificial neural network) and scientific theorems (if then statements and logics). AI technologies have matured to the point in offering real practical benefits in many of their applications. Major artificial intelligence areas are Expert systems, Intelligent computer aided instructions, Natural language processing, Speech understanding, Robotics and sensory systems, Computer vision and scene recognition, Neural computing. From these expert system is a rapidly growing technology which is heaving a huge impact on various field of life. The various techniques applied in artificial intelligence are Neural network, Fuzzy logic, Evolutionary computing, Computer aided instructions and Hybrid artificial intelligence", "Artificial intelligence has the advantages over the natural intelligence as it is more permanent, consistent, less expensive, has the ease of duplication and dissemination, can be documented and can perform certain tasks much faster and better than human. Thus is effective in educational technology to make the teaching learning process more effective and concrete with the help of various artificial intelligence teaching techniques."],
                            secImage: "/images/paperImage/image1.jpg",
                            secImageCaption: "Papers published on different AI techniques quarterly",
                        },
                        {
                            secTitle: "Meaning of artificial intelligence",
                            secContent: ["Artificial intelligence is the combination of two words artificial + intelligence. Where artificial means ‘not real’ or ‘natural’ and by intelligence means ‘the ability to reason, to trigger new thoughts, to perceive and learn’.It is effective in educational technology to make the teaching learning process more effective and concrete with the help of various artificial intelligence teaching techniques. Artificial intelligence can be defined that area of computer science that mainly focus on the making on such kind of intelligent machines that work and give reactions same like human beings. It is combination of many activities which includes for designing the artificial in computers that are like-recognizing the speech, learning, planning and solving the problem. When any system adapts itself according to situation in any environment is called intelligent.", "In other words, it can be defined as programming such machines which can think and act with some level of human intelligence is known as artificial intelligence. Artificial intelligence can be defined as efficiently use of limited resources. So artificial intelligence can be defined as making computer programs to solve complex problems same like as human solve the problems. So it is also divided into two parts one is to solving complex problems by the machine and second is same like human beings. The term artificial intelligence is also used to describe a property of machines or programs: the intelligence that the system demonstrates. Artificial intelligence is combination of science and engineering for making the machines which behaves in intelligent manner. In it many fields are combined like philosophy, psychology and computer science."],
                            secImage: "/images/paperImage/image2.jpg",
                            secImageCaption: " Working of a search engine",

                        },
                        {
                            secTitle: "Scope of artificial intelligence in different areas",
                            secContent: [],
                            subSection: [
                                {
                                    subSectionTitle: "In the field of education",
                                    subSectionContent: [],
                                    subSubSection: [{
                                        subsubSectionTitle: "Artificial intelligence can automate basic activities in education, like grading",
                                        subsubSectionContent: ["While AI may not ever be able to truly replace human grading, it’s getting pretty close. It’s now possible for teachers to automate grading for nearly all kinds of multiple choice and fill-in-the-blank testing and automated grading of student writing may not be far behind. Today, essay-grading software is still in its infancy and not quite up to par, yet it in college, grading homework and tests for large lecture courses can be tedious work, even when TAs split it between them. Even in lower grades, teachers often find that grading takes up a significant amount of time, time that could be used to interact with students, prepare for class, or work on professional development."],
                                    },
                                    {
                                        subsubSectionTitle: "Educational software can be adapted to student needs",
                                        subsubSectionContent: ["From kindergarten to graduate school, one of the key ways artificial intelligence will impact education is through the application of greater levels of individualized learning. Some of this is already happening through growing numbers of adaptive learning programs, games, and software. These systems respond to the needs of the student, putting greater emphasis on certain topics, repeating things that students haven’t mastered, and generally helping students to work at their own pace, whatever that may be. This kind of custom tailored education could be a machine-assisted solution to helping students at different levels work together in one classroom, with teachers facilitating the learning and offering help and support when needed.", "Adaptive learning has already had a huge impact on education across the nation (especially through programs like Khan Academy), and as AI advances in the coming decades adaptive programs like these will likely only improve and expand."],
                                    },]
                                },
                                {
                                    subSectionTitle: "Language understanding",
                                    subSectionContent: ["Teachers may not always be aware of gaps in their lectures and educational materials that can leave students confused about certain concepts. Artificial intelligence offers a way to solve that problem. Coursera, a massive open online course provider, is already putting this into practice. When a large number  of students are found to submit the wrong answer to a homework assignment, the system alerts the teacher and gives future students a customized message that offers hints to the correct answer. This type of system helps to fill in the gaps in explanation that can occur in courses, and helps to ensure that all students are building the same conceptual foundation. Rather than waiting to hear back from the professor, students get immediate feedback that helps them to understand a concept and remember how to do it correctly the next time around.", "The ability to 'understand' and respond to the natural language. To translate from spoken language to a written form and to translate from one natural language to another natural language."],
                                    subSectionImage: "/images/paperImage/image3.jpg",
                                    subSectionImageCaption: "Working of a search engine",
                                },]
                        },
                        {
                            secTitle: "Searching techniques in artificial intelligence",
                            secContent: ["In AI for finding the solution of problem searching has to be done because solution is not known in advance. For it AI programs are developed which do the searching process for solution because solution steps are not known before hand and have to be found out. For doing searching following steps are required. So we can say that searching is a process which transform initial state to goal state."],
                        },
                        {
                            secTitle: "Conclusion",
                            secContent: ["The field of artificial intelligence gives the ability to the machines to think analytically, using concepts. Tremendous contribution to the various areas has been made by the Artificial Intelligence techniques from the last 2 decades. Artificial Intelligence will continue to play an increasingly important role in the various fields. This paper is based on the concept of artificial intelligence, scope of artificial intelligence in different areas with special to “the field of education”. As all know artificial intelligence is intelligence behavior of machines which is given by the professional. As you all know artificial intelligence have simplified our life in every aspect it can be article writing or game playing or taking any important decision. In any machine many experts mind can be combined which is more powerful than a single expert mind.", "Many labors work can be done by a single machine and good thing of it is that it never tired. Now such types of robots are going to make which have emotions it will finish the loneliness of the person. But it has another aspect that is can be dangers for us. If we become completely dependent on that machines than it can ruin our life as we do not do any work ourselves and got lazy. And another is that it cannot give the feeling like human. So machines should be used only where there those are actually required."],

                        },
                    ],
                    reference: ["Ramesh N, Kambhampati C, Monson JRT, Drew PJ. Artificial intelligence, 2004.", "Sampada C et al. Adaptive Neuro-Fuzzy Intrusion Detection Systems, Proceedings: International Conference on Information Technology: Coding and Computing ITCC 04, 2004.", "Deepa SN, Aruna Devi B. A survey on intelligence approaches for medical image  Indian Journal of Science and Technology, 2011; 4(11).", "Zadeh L. Fuzzy sets Inf Control, IJET, 2014.", "Joanna Bryson and Jeremy Wyatt. Artificial Intelligence Retrieved from: http://www.cs.bath.ac .uk/~jjb/web/whatisai.html, 1997."]
                }
            },
            {
                id: "3",
                type: "blog",
                createdAt: "July 03, 2024",
                thumbnailImage: "/images/blogImage/React-image.jpg",
                excerpt: ["Designed to encapsulate and manage the user interface (UI) in a modular, reusable manner.", "React components are the fundamental building blocks of React applications, designed to encapsulate and manage the user interface (UI) in a modular, reusable manner. This blog explores the core concepts behind React components, their importance, and best practices for their implementation."],
                title: "1.3Artificial intelligence and its scope in different areas with special reference to the field of education",
                body: {
                    writers: ["John Doe"],
                    address: "Department of Education, Rama PG College, University of Lucknow, Chinhat, Lucknow, Uttar Pradesh, India",
                    abstract: ["In the future, intelligent machines will replace or enhance human capabilities in many areas. Artificial intelligence is the intelligence exhibited by machines or software. It is the subfield of computer science. Artificial intelligence is becoming a popular field in computer science as it has enhanced the human life in many areas. Artificial intelligence in the last two decades has greatly improved performance of the manufacturing, service sector and so in the field of education. Study in the field of artificial intelligence has given rise to the rapidly growing technology known as expert system. Application areas of artificial intelligence is heaving a huge impact on various fields of life as expert system is widely used in these days to solve the complex problems in various areas as education, engineering, business, medicine, weather forecasting etc. The areas employing the technology of artificial intelligence have seen an increase in the quality and efficiency. This paper gives an overview of this technology and the scope of artificial intelligence in different areas with special reference to the use of this technology in the field of education along with its meaning, searching techniques, inventions and future.",],
                    keywords: ["artificial intelligence (AI)", "artificial neurons (neural computer networks)", "expert system", "heuristic", "searching techniques",],
                    contents: [
                        {
                            secTitle: "Introduction",
                            secContent: ["It is claimed that artificial intelligence is playing an increasing role in the research of educational technology, management sciences and operational research areas. Intelligence is commonly considered as the ability to collect knowledge to solve complex problems. In the near future intelligent machines will replace human capabilities in many areas. Artificial intelligence is the study of intelligent machines and software that can reason, learn, gather knowledge, communicate, manipulate and perceive the objects. John McCarthy coined the term in 1956 as branch of computer science concerned with making computers behave like humans. It is the study of the computation that makes it possible to perceive reason and act. Artificial intelligence is different from Psychology because it emphasis on computation and is different from computer science because of its emphasis on perception, reasoning and action.", "It makes machines smarter and more useful. It works with the help of artificial neurons (artificial neural network) and scientific theorems (if then statements and logics). AI technologies have matured to the point in offering real practical benefits in many of their applications. Major artificial intelligence areas are Expert systems, Intelligent computer aided instructions, Natural language processing, Speech understanding, Robotics and sensory systems, Computer vision and scene recognition, Neural computing. From these expert system is a rapidly growing technology which is heaving a huge impact on various field of life. The various techniques applied in artificial intelligence are Neural network, Fuzzy logic, Evolutionary computing, Computer aided instructions and Hybrid artificial intelligence", "Artificial intelligence has the advantages over the natural intelligence as it is more permanent, consistent, less expensive, has the ease of duplication and dissemination, can be documented and can perform certain tasks much faster and better than human. Thus is effective in educational technology to make the teaching learning process more effective and concrete with the help of various artificial intelligence teaching techniques."],
                            secImage: "/images/paperImage/image1.jpg",
                            secImageCaption: "Papers published on different AI techniques quarterly",
                        },
                        {
                            secTitle: "Meaning of artificial intelligence",
                            secContent: ["Artificial intelligence is the combination of two words artificial + intelligence. Where artificial means ‘not real’ or ‘natural’ and by intelligence means ‘the ability to reason, to trigger new thoughts, to perceive and learn’.It is effective in educational technology to make the teaching learning process more effective and concrete with the help of various artificial intelligence teaching techniques. Artificial intelligence can be defined that area of computer science that mainly focus on the making on such kind of intelligent machines that work and give reactions same like human beings. It is combination of many activities which includes for designing the artificial in computers that are like-recognizing the speech, learning, planning and solving the problem. When any system adapts itself according to situation in any environment is called intelligent.", "In other words, it can be defined as programming such machines which can think and act with some level of human intelligence is known as artificial intelligence. Artificial intelligence can be defined as efficiently use of limited resources. So artificial intelligence can be defined as making computer programs to solve complex problems same like as human solve the problems. So it is also divided into two parts one is to solving complex problems by the machine and second is same like human beings. The term artificial intelligence is also used to describe a property of machines or programs: the intelligence that the system demonstrates. Artificial intelligence is combination of science and engineering for making the machines which behaves in intelligent manner. In it many fields are combined like philosophy, psychology and computer science."],
                            secImage: "/images/paperImage/image2.jpg",
                            secImageCaption: " Working of a search engine",

                        },
                        {
                            secTitle: "Scope of artificial intelligence in different areas",
                            secContent: [],
                            subSection: [
                                {
                                    subSectionTitle: "In the field of education",
                                    subSectionContent: [],
                                    subSubSection: [{
                                        subsubSectionTitle: "Artificial intelligence can automate basic activities in education, like grading",
                                        subsubSectionContent: ["While AI may not ever be able to truly replace human grading, it’s getting pretty close. It’s now possible for teachers to automate grading for nearly all kinds of multiple choice and fill-in-the-blank testing and automated grading of student writing may not be far behind. Today, essay-grading software is still in its infancy and not quite up to par, yet it in college, grading homework and tests for large lecture courses can be tedious work, even when TAs split it between them. Even in lower grades, teachers often find that grading takes up a significant amount of time, time that could be used to interact with students, prepare for class, or work on professional development."],
                                    },
                                    {
                                        subsubSectionTitle: "Educational software can be adapted to student needs",
                                        subsubSectionContent: ["From kindergarten to graduate school, one of the key ways artificial intelligence will impact education is through the application of greater levels of individualized learning. Some of this is already happening through growing numbers of adaptive learning programs, games, and software. These systems respond to the needs of the student, putting greater emphasis on certain topics, repeating things that students haven’t mastered, and generally helping students to work at their own pace, whatever that may be. This kind of custom tailored education could be a machine-assisted solution to helping students at different levels work together in one classroom, with teachers facilitating the learning and offering help and support when needed.", "Adaptive learning has already had a huge impact on education across the nation (especially through programs like Khan Academy), and as AI advances in the coming decades adaptive programs like these will likely only improve and expand."],
                                    },]
                                },
                                {
                                    subSectionTitle: "Language understanding",
                                    subSectionContent: ["Teachers may not always be aware of gaps in their lectures and educational materials that can leave students confused about certain concepts. Artificial intelligence offers a way to solve that problem. Coursera, a massive open online course provider, is already putting this into practice. When a large number  of students are found to submit the wrong answer to a homework assignment, the system alerts the teacher and gives future students a customized message that offers hints to the correct answer. This type of system helps to fill in the gaps in explanation that can occur in courses, and helps to ensure that all students are building the same conceptual foundation. Rather than waiting to hear back from the professor, students get immediate feedback that helps them to understand a concept and remember how to do it correctly the next time around.", "The ability to 'understand' and respond to the natural language. To translate from spoken language to a written form and to translate from one natural language to another natural language."],
                                    subSectionImage: "/images/paperImage/image3.jpg",
                                    subSectionImageCaption: "Working of a search engine",
                                },]
                        },
                        {
                            secTitle: "Searching techniques in artificial intelligence",
                            secContent: ["In AI for finding the solution of problem searching has to be done because solution is not known in advance. For it AI programs are developed which do the searching process for solution because solution steps are not known before hand and have to be found out. For doing searching following steps are required. So we can say that searching is a process which transform initial state to goal state."],
                        },
                        {
                            secTitle: "Conclusion",
                            secContent: ["The field of artificial intelligence gives the ability to the machines to think analytically, using concepts. Tremendous contribution to the various areas has been made by the Artificial Intelligence techniques from the last 2 decades. Artificial Intelligence will continue to play an increasingly important role in the various fields. This paper is based on the concept of artificial intelligence, scope of artificial intelligence in different areas with special to “the field of education”. As all know artificial intelligence is intelligence behavior of machines which is given by the professional. As you all know artificial intelligence have simplified our life in every aspect it can be article writing or game playing or taking any important decision. In any machine many experts mind can be combined which is more powerful than a single expert mind.", "Many labors work can be done by a single machine and good thing of it is that it never tired. Now such types of robots are going to make which have emotions it will finish the loneliness of the person. But it has another aspect that is can be dangers for us. If we become completely dependent on that machines than it can ruin our life as we do not do any work ourselves and got lazy. And another is that it cannot give the feeling like human. So machines should be used only where there those are actually required."],

                        },
                    ],
                    reference: ["Ramesh N, Kambhampati C, Monson JRT, Drew PJ. Artificial intelligence, 2004.", "Sampada C et al. Adaptive Neuro-Fuzzy Intrusion Detection Systems, Proceedings: International Conference on Information Technology: Coding and Computing ITCC 04, 2004.", "Deepa SN, Aruna Devi B. A survey on intelligence approaches for medical image  Indian Journal of Science and Technology, 2011; 4(11).", "Zadeh L. Fuzzy sets Inf Control, IJET, 2014.", "Joanna Bryson and Jeremy Wyatt. Artificial Intelligence Retrieved from: http://www.cs.bath.ac .uk/~jjb/web/whatisai.html, 1997."]
                }
            },
        ]
    },
    {
        subjectId: "2",
        subjectTitle: "2Artificial Intelligence",
        subjectExcerpt: [
            "React is an open-source JavaScript library developed by Facebook for building user interfaces, particularly single-page applications where a dynamic and high-performing user experience is crucial.",
            "It focuses on the view layer of the MVC (Model-View-Controller) architecture and enables developers to create reusable UI components. "
        ],
        subjectCardImage: "/images/paperImage/AI1.jpg",
        subjectPageImage: "/images/paperImage/AI2.jpg",
        subjectPageIntro: ["React is a framework that employs Webpack to automatically compile React, JSX, and ES6 code while handling CSS file prefixes. React is a JavaScript-based UI development library. Although React is a library rather than a language, it is widely used in web development. The library first appeared in May 2013 and is now one of the most commonly used frontend libraries for web development.", "React offers various extensions for entire application architectural support, such as Flux and React Native, beyond mere UI.",],
        chapters: [
            {
                id: "1",
                type: "blog",
                createdAt: "July 03, 2024",
                thumbnailImage: "/images/blogImage/React-image.jpg",
                excerpt: ["Designed to encapsulate and manage the user interface (UI) in a modular, reusable manner.", "React components are the fundamental building blocks of React applications, designed to encapsulate and manage the user interface (UI) in a modular, reusable manner. This blog explores the core concepts behind React components, their importance, and best practices for their implementation."],
                title: "2.1Artificial intelligence and its scope in different areas with special reference to the field of education",
                body: {
                    writers: ["John Doe"],
                    address: "Department of Education, Rama PG College, University of Lucknow, Chinhat, Lucknow, Uttar Pradesh, India",
                    abstract: ["In the future, intelligent machines will replace or enhance human capabilities in many areas. Artificial intelligence is the intelligence exhibited by machines or software. It is the subfield of computer science. Artificial intelligence is becoming a popular field in computer science as it has enhanced the human life in many areas. Artificial intelligence in the last two decades has greatly improved performance of the manufacturing, service sector and so in the field of education. Study in the field of artificial intelligence has given rise to the rapidly growing technology known as expert system. Application areas of artificial intelligence is heaving a huge impact on various fields of life as expert system is widely used in these days to solve the complex problems in various areas as education, engineering, business, medicine, weather forecasting etc. The areas employing the technology of artificial intelligence have seen an increase in the quality and efficiency. This paper gives an overview of this technology and the scope of artificial intelligence in different areas with special reference to the use of this technology in the field of education along with its meaning, searching techniques, inventions and future.",],
                    keywords: ["artificial intelligence (AI)", "artificial neurons (neural computer networks)", "expert system", "heuristic", "searching techniques",],
                    contents: [
                        {
                            secTitle: "Introduction",
                            secContent: ["It is claimed that artificial intelligence is playing an increasing role in the research of educational technology, management sciences and operational research areas. Intelligence is commonly considered as the ability to collect knowledge to solve complex problems. In the near future intelligent machines will replace human capabilities in many areas. Artificial intelligence is the study of intelligent machines and software that can reason, learn, gather knowledge, communicate, manipulate and perceive the objects. John McCarthy coined the term in 1956 as branch of computer science concerned with making computers behave like humans. It is the study of the computation that makes it possible to perceive reason and act. Artificial intelligence is different from Psychology because it emphasis on computation and is different from computer science because of its emphasis on perception, reasoning and action.", "It makes machines smarter and more useful. It works with the help of artificial neurons (artificial neural network) and scientific theorems (if then statements and logics). AI technologies have matured to the point in offering real practical benefits in many of their applications. Major artificial intelligence areas are Expert systems, Intelligent computer aided instructions, Natural language processing, Speech understanding, Robotics and sensory systems, Computer vision and scene recognition, Neural computing. From these expert system is a rapidly growing technology which is heaving a huge impact on various field of life. The various techniques applied in artificial intelligence are Neural network, Fuzzy logic, Evolutionary computing, Computer aided instructions and Hybrid artificial intelligence", "Artificial intelligence has the advantages over the natural intelligence as it is more permanent, consistent, less expensive, has the ease of duplication and dissemination, can be documented and can perform certain tasks much faster and better than human. Thus is effective in educational technology to make the teaching learning process more effective and concrete with the help of various artificial intelligence teaching techniques."],
                            secImage: "/images/paperImage/image1.jpg",
                            secImageCaption: "Papers published on different AI techniques quarterly",
                        },
                        {
                            secTitle: "Meaning of artificial intelligence",
                            secContent: ["Artificial intelligence is the combination of two words artificial + intelligence. Where artificial means ‘not real’ or ‘natural’ and by intelligence means ‘the ability to reason, to trigger new thoughts, to perceive and learn’.It is effective in educational technology to make the teaching learning process more effective and concrete with the help of various artificial intelligence teaching techniques. Artificial intelligence can be defined that area of computer science that mainly focus on the making on such kind of intelligent machines that work and give reactions same like human beings. It is combination of many activities which includes for designing the artificial in computers that are like-recognizing the speech, learning, planning and solving the problem. When any system adapts itself according to situation in any environment is called intelligent.", "In other words, it can be defined as programming such machines which can think and act with some level of human intelligence is known as artificial intelligence. Artificial intelligence can be defined as efficiently use of limited resources. So artificial intelligence can be defined as making computer programs to solve complex problems same like as human solve the problems. So it is also divided into two parts one is to solving complex problems by the machine and second is same like human beings. The term artificial intelligence is also used to describe a property of machines or programs: the intelligence that the system demonstrates. Artificial intelligence is combination of science and engineering for making the machines which behaves in intelligent manner. In it many fields are combined like philosophy, psychology and computer science."],
                            secImage: "/images/paperImage/image2.jpg",
                            secImageCaption: " Working of a search engine",

                        },
                        {
                            secTitle: "Scope of artificial intelligence in different areas",
                            secContent: [],
                            subSection: [
                                {
                                    subSectionTitle: "In the field of education",
                                    subSectionContent: [],
                                    subSubSection: [{
                                        subsubSectionTitle: "Artificial intelligence can automate basic activities in education, like grading",
                                        subsubSectionContent: ["While AI may not ever be able to truly replace human grading, it’s getting pretty close. It’s now possible for teachers to automate grading for nearly all kinds of multiple choice and fill-in-the-blank testing and automated grading of student writing may not be far behind. Today, essay-grading software is still in its infancy and not quite up to par, yet it in college, grading homework and tests for large lecture courses can be tedious work, even when TAs split it between them. Even in lower grades, teachers often find that grading takes up a significant amount of time, time that could be used to interact with students, prepare for class, or work on professional development."],
                                    },
                                    {
                                        subsubSectionTitle: "Educational software can be adapted to student needs",
                                        subsubSectionContent: ["From kindergarten to graduate school, one of the key ways artificial intelligence will impact education is through the application of greater levels of individualized learning. Some of this is already happening through growing numbers of adaptive learning programs, games, and software. These systems respond to the needs of the student, putting greater emphasis on certain topics, repeating things that students haven’t mastered, and generally helping students to work at their own pace, whatever that may be. This kind of custom tailored education could be a machine-assisted solution to helping students at different levels work together in one classroom, with teachers facilitating the learning and offering help and support when needed.", "Adaptive learning has already had a huge impact on education across the nation (especially through programs like Khan Academy), and as AI advances in the coming decades adaptive programs like these will likely only improve and expand."],
                                    },]
                                },
                                {
                                    subSectionTitle: "Language understanding",
                                    subSectionContent: ["Teachers may not always be aware of gaps in their lectures and educational materials that can leave students confused about certain concepts. Artificial intelligence offers a way to solve that problem. Coursera, a massive open online course provider, is already putting this into practice. When a large number  of students are found to submit the wrong answer to a homework assignment, the system alerts the teacher and gives future students a customized message that offers hints to the correct answer. This type of system helps to fill in the gaps in explanation that can occur in courses, and helps to ensure that all students are building the same conceptual foundation. Rather than waiting to hear back from the professor, students get immediate feedback that helps them to understand a concept and remember how to do it correctly the next time around.", "The ability to 'understand' and respond to the natural language. To translate from spoken language to a written form and to translate from one natural language to another natural language."],
                                    subSectionImage: "/images/paperImage/image3.jpg",
                                    subSectionImageCaption: "Working of a search engine",
                                },]
                        },
                        {
                            secTitle: "Searching techniques in artificial intelligence",
                            secContent: ["In AI for finding the solution of problem searching has to be done because solution is not known in advance. For it AI programs are developed which do the searching process for solution because solution steps are not known before hand and have to be found out. For doing searching following steps are required. So we can say that searching is a process which transform initial state to goal state."],
                        },
                        {
                            secTitle: "Conclusion",
                            secContent: ["The field of artificial intelligence gives the ability to the machines to think analytically, using concepts. Tremendous contribution to the various areas has been made by the Artificial Intelligence techniques from the last 2 decades. Artificial Intelligence will continue to play an increasingly important role in the various fields. This paper is based on the concept of artificial intelligence, scope of artificial intelligence in different areas with special to “the field of education”. As all know artificial intelligence is intelligence behavior of machines which is given by the professional. As you all know artificial intelligence have simplified our life in every aspect it can be article writing or game playing or taking any important decision. In any machine many experts mind can be combined which is more powerful than a single expert mind.", "Many labors work can be done by a single machine and good thing of it is that it never tired. Now such types of robots are going to make which have emotions it will finish the loneliness of the person. But it has another aspect that is can be dangers for us. If we become completely dependent on that machines than it can ruin our life as we do not do any work ourselves and got lazy. And another is that it cannot give the feeling like human. So machines should be used only where there those are actually required."],

                        },
                    ],
                    reference: ["Ramesh N, Kambhampati C, Monson JRT, Drew PJ. Artificial intelligence, 2004.", "Sampada C et al. Adaptive Neuro-Fuzzy Intrusion Detection Systems, Proceedings: International Conference on Information Technology: Coding and Computing ITCC 04, 2004.", "Deepa SN, Aruna Devi B. A survey on intelligence approaches for medical image  Indian Journal of Science and Technology, 2011; 4(11).", "Zadeh L. Fuzzy sets Inf Control, IJET, 2014.", "Joanna Bryson and Jeremy Wyatt. Artificial Intelligence Retrieved from: http://www.cs.bath.ac .uk/~jjb/web/whatisai.html, 1997."]
                }
            },
            {
                id: "2",
                type: "blog",
                createdAt: "July 03, 2024",
                thumbnailImage: "/images/blogImage/React-image.jpg",
                excerpt: ["Designed to encapsulate and manage the user interface (UI) in a modular, reusable manner.", "React components are the fundamental building blocks of React applications, designed to encapsulate and manage the user interface (UI) in a modular, reusable manner. This blog explores the core concepts behind React components, their importance, and best practices for their implementation."],
                title: "2.2Artificial intelligence and its scope in different areas with special reference to the field of education",
                body: {
                    writers: ["John Doe"],
                    address: "Department of Education, Rama PG College, University of Lucknow, Chinhat, Lucknow, Uttar Pradesh, India",
                    abstract: ["In the future, intelligent machines will replace or enhance human capabilities in many areas. Artificial intelligence is the intelligence exhibited by machines or software. It is the subfield of computer science. Artificial intelligence is becoming a popular field in computer science as it has enhanced the human life in many areas. Artificial intelligence in the last two decades has greatly improved performance of the manufacturing, service sector and so in the field of education. Study in the field of artificial intelligence has given rise to the rapidly growing technology known as expert system. Application areas of artificial intelligence is heaving a huge impact on various fields of life as expert system is widely used in these days to solve the complex problems in various areas as education, engineering, business, medicine, weather forecasting etc. The areas employing the technology of artificial intelligence have seen an increase in the quality and efficiency. This paper gives an overview of this technology and the scope of artificial intelligence in different areas with special reference to the use of this technology in the field of education along with its meaning, searching techniques, inventions and future.",],
                    keywords: ["artificial intelligence (AI)", "artificial neurons (neural computer networks)", "expert system", "heuristic", "searching techniques",],
                    contents: [
                        {
                            secTitle: "Introduction",
                            secContent: ["It is claimed that artificial intelligence is playing an increasing role in the research of educational technology, management sciences and operational research areas. Intelligence is commonly considered as the ability to collect knowledge to solve complex problems. In the near future intelligent machines will replace human capabilities in many areas. Artificial intelligence is the study of intelligent machines and software that can reason, learn, gather knowledge, communicate, manipulate and perceive the objects. John McCarthy coined the term in 1956 as branch of computer science concerned with making computers behave like humans. It is the study of the computation that makes it possible to perceive reason and act. Artificial intelligence is different from Psychology because it emphasis on computation and is different from computer science because of its emphasis on perception, reasoning and action.", "It makes machines smarter and more useful. It works with the help of artificial neurons (artificial neural network) and scientific theorems (if then statements and logics). AI technologies have matured to the point in offering real practical benefits in many of their applications. Major artificial intelligence areas are Expert systems, Intelligent computer aided instructions, Natural language processing, Speech understanding, Robotics and sensory systems, Computer vision and scene recognition, Neural computing. From these expert system is a rapidly growing technology which is heaving a huge impact on various field of life. The various techniques applied in artificial intelligence are Neural network, Fuzzy logic, Evolutionary computing, Computer aided instructions and Hybrid artificial intelligence", "Artificial intelligence has the advantages over the natural intelligence as it is more permanent, consistent, less expensive, has the ease of duplication and dissemination, can be documented and can perform certain tasks much faster and better than human. Thus is effective in educational technology to make the teaching learning process more effective and concrete with the help of various artificial intelligence teaching techniques."],
                            secImage: "/images/paperImage/image1.jpg",
                            secImageCaption: "Papers published on different AI techniques quarterly",
                        },
                        {
                            secTitle: "Meaning of artificial intelligence",
                            secContent: ["Artificial intelligence is the combination of two words artificial + intelligence. Where artificial means ‘not real’ or ‘natural’ and by intelligence means ‘the ability to reason, to trigger new thoughts, to perceive and learn’.It is effective in educational technology to make the teaching learning process more effective and concrete with the help of various artificial intelligence teaching techniques. Artificial intelligence can be defined that area of computer science that mainly focus on the making on such kind of intelligent machines that work and give reactions same like human beings. It is combination of many activities which includes for designing the artificial in computers that are like-recognizing the speech, learning, planning and solving the problem. When any system adapts itself according to situation in any environment is called intelligent.", "In other words, it can be defined as programming such machines which can think and act with some level of human intelligence is known as artificial intelligence. Artificial intelligence can be defined as efficiently use of limited resources. So artificial intelligence can be defined as making computer programs to solve complex problems same like as human solve the problems. So it is also divided into two parts one is to solving complex problems by the machine and second is same like human beings. The term artificial intelligence is also used to describe a property of machines or programs: the intelligence that the system demonstrates. Artificial intelligence is combination of science and engineering for making the machines which behaves in intelligent manner. In it many fields are combined like philosophy, psychology and computer science."],
                            secImage: "/images/paperImage/image2.jpg",
                            secImageCaption: " Working of a search engine",

                        },
                        {
                            secTitle: "Scope of artificial intelligence in different areas",
                            secContent: [],
                            subSection: [
                                {
                                    subSectionTitle: "In the field of education",
                                    subSectionContent: [],
                                    subSubSection: [{
                                        subsubSectionTitle: "Artificial intelligence can automate basic activities in education, like grading",
                                        subsubSectionContent: ["While AI may not ever be able to truly replace human grading, it’s getting pretty close. It’s now possible for teachers to automate grading for nearly all kinds of multiple choice and fill-in-the-blank testing and automated grading of student writing may not be far behind. Today, essay-grading software is still in its infancy and not quite up to par, yet it in college, grading homework and tests for large lecture courses can be tedious work, even when TAs split it between them. Even in lower grades, teachers often find that grading takes up a significant amount of time, time that could be used to interact with students, prepare for class, or work on professional development."],
                                    },
                                    {
                                        subsubSectionTitle: "Educational software can be adapted to student needs",
                                        subsubSectionContent: ["From kindergarten to graduate school, one of the key ways artificial intelligence will impact education is through the application of greater levels of individualized learning. Some of this is already happening through growing numbers of adaptive learning programs, games, and software. These systems respond to the needs of the student, putting greater emphasis on certain topics, repeating things that students haven’t mastered, and generally helping students to work at their own pace, whatever that may be. This kind of custom tailored education could be a machine-assisted solution to helping students at different levels work together in one classroom, with teachers facilitating the learning and offering help and support when needed.", "Adaptive learning has already had a huge impact on education across the nation (especially through programs like Khan Academy), and as AI advances in the coming decades adaptive programs like these will likely only improve and expand."],
                                    },]
                                },
                                {
                                    subSectionTitle: "Language understanding",
                                    subSectionContent: ["Teachers may not always be aware of gaps in their lectures and educational materials that can leave students confused about certain concepts. Artificial intelligence offers a way to solve that problem. Coursera, a massive open online course provider, is already putting this into practice. When a large number  of students are found to submit the wrong answer to a homework assignment, the system alerts the teacher and gives future students a customized message that offers hints to the correct answer. This type of system helps to fill in the gaps in explanation that can occur in courses, and helps to ensure that all students are building the same conceptual foundation. Rather than waiting to hear back from the professor, students get immediate feedback that helps them to understand a concept and remember how to do it correctly the next time around.", "The ability to 'understand' and respond to the natural language. To translate from spoken language to a written form and to translate from one natural language to another natural language."],
                                    subSectionImage: "/images/paperImage/image3.jpg",
                                    subSectionImageCaption: "Working of a search engine",
                                },]
                        },
                        {
                            secTitle: "Searching techniques in artificial intelligence",
                            secContent: ["In AI for finding the solution of problem searching has to be done because solution is not known in advance. For it AI programs are developed which do the searching process for solution because solution steps are not known before hand and have to be found out. For doing searching following steps are required. So we can say that searching is a process which transform initial state to goal state."],
                        },
                        {
                            secTitle: "Conclusion",
                            secContent: ["The field of artificial intelligence gives the ability to the machines to think analytically, using concepts. Tremendous contribution to the various areas has been made by the Artificial Intelligence techniques from the last 2 decades. Artificial Intelligence will continue to play an increasingly important role in the various fields. This paper is based on the concept of artificial intelligence, scope of artificial intelligence in different areas with special to “the field of education”. As all know artificial intelligence is intelligence behavior of machines which is given by the professional. As you all know artificial intelligence have simplified our life in every aspect it can be article writing or game playing or taking any important decision. In any machine many experts mind can be combined which is more powerful than a single expert mind.", "Many labors work can be done by a single machine and good thing of it is that it never tired. Now such types of robots are going to make which have emotions it will finish the loneliness of the person. But it has another aspect that is can be dangers for us. If we become completely dependent on that machines than it can ruin our life as we do not do any work ourselves and got lazy. And another is that it cannot give the feeling like human. So machines should be used only where there those are actually required."],

                        },
                    ],
                    reference: ["Ramesh N, Kambhampati C, Monson JRT, Drew PJ. Artificial intelligence, 2004.", "Sampada C et al. Adaptive Neuro-Fuzzy Intrusion Detection Systems, Proceedings: International Conference on Information Technology: Coding and Computing ITCC 04, 2004.", "Deepa SN, Aruna Devi B. A survey on intelligence approaches for medical image  Indian Journal of Science and Technology, 2011; 4(11).", "Zadeh L. Fuzzy sets Inf Control, IJET, 2014.", "Joanna Bryson and Jeremy Wyatt. Artificial Intelligence Retrieved from: http://www.cs.bath.ac .uk/~jjb/web/whatisai.html, 1997."]
                }
            },
            {
                id: "3",
                type: "blog",
                createdAt: "July 03, 2024",
                thumbnailImage: "/images/blogImage/React-image.jpg",
                excerpt: ["Designed to encapsulate and manage the user interface (UI) in a modular, reusable manner.", "React components are the fundamental building blocks of React applications, designed to encapsulate and manage the user interface (UI) in a modular, reusable manner. This blog explores the core concepts behind React components, their importance, and best practices for their implementation."],
                title: "2.3Artificial intelligence and its scope in different areas with special reference to the field of education",
                body: {
                    writers: ["John Doe"],
                    address: "Department of Education, Rama PG College, University of Lucknow, Chinhat, Lucknow, Uttar Pradesh, India",
                    abstract: ["In the future, intelligent machines will replace or enhance human capabilities in many areas. Artificial intelligence is the intelligence exhibited by machines or software. It is the subfield of computer science. Artificial intelligence is becoming a popular field in computer science as it has enhanced the human life in many areas. Artificial intelligence in the last two decades has greatly improved performance of the manufacturing, service sector and so in the field of education. Study in the field of artificial intelligence has given rise to the rapidly growing technology known as expert system. Application areas of artificial intelligence is heaving a huge impact on various fields of life as expert system is widely used in these days to solve the complex problems in various areas as education, engineering, business, medicine, weather forecasting etc. The areas employing the technology of artificial intelligence have seen an increase in the quality and efficiency. This paper gives an overview of this technology and the scope of artificial intelligence in different areas with special reference to the use of this technology in the field of education along with its meaning, searching techniques, inventions and future.",],
                    keywords: ["artificial intelligence (AI)", "artificial neurons (neural computer networks)", "expert system", "heuristic", "searching techniques",],
                    contents: [
                        {
                            secTitle: "Introduction",
                            secContent: ["It is claimed that artificial intelligence is playing an increasing role in the research of educational technology, management sciences and operational research areas. Intelligence is commonly considered as the ability to collect knowledge to solve complex problems. In the near future intelligent machines will replace human capabilities in many areas. Artificial intelligence is the study of intelligent machines and software that can reason, learn, gather knowledge, communicate, manipulate and perceive the objects. John McCarthy coined the term in 1956 as branch of computer science concerned with making computers behave like humans. It is the study of the computation that makes it possible to perceive reason and act. Artificial intelligence is different from Psychology because it emphasis on computation and is different from computer science because of its emphasis on perception, reasoning and action.", "It makes machines smarter and more useful. It works with the help of artificial neurons (artificial neural network) and scientific theorems (if then statements and logics). AI technologies have matured to the point in offering real practical benefits in many of their applications. Major artificial intelligence areas are Expert systems, Intelligent computer aided instructions, Natural language processing, Speech understanding, Robotics and sensory systems, Computer vision and scene recognition, Neural computing. From these expert system is a rapidly growing technology which is heaving a huge impact on various field of life. The various techniques applied in artificial intelligence are Neural network, Fuzzy logic, Evolutionary computing, Computer aided instructions and Hybrid artificial intelligence", "Artificial intelligence has the advantages over the natural intelligence as it is more permanent, consistent, less expensive, has the ease of duplication and dissemination, can be documented and can perform certain tasks much faster and better than human. Thus is effective in educational technology to make the teaching learning process more effective and concrete with the help of various artificial intelligence teaching techniques."],
                            secImage: "/images/paperImage/image1.jpg",
                            secImageCaption: "Papers published on different AI techniques quarterly",
                        },
                        {
                            secTitle: "Meaning of artificial intelligence",
                            secContent: ["Artificial intelligence is the combination of two words artificial + intelligence. Where artificial means ‘not real’ or ‘natural’ and by intelligence means ‘the ability to reason, to trigger new thoughts, to perceive and learn’.It is effective in educational technology to make the teaching learning process more effective and concrete with the help of various artificial intelligence teaching techniques. Artificial intelligence can be defined that area of computer science that mainly focus on the making on such kind of intelligent machines that work and give reactions same like human beings. It is combination of many activities which includes for designing the artificial in computers that are like-recognizing the speech, learning, planning and solving the problem. When any system adapts itself according to situation in any environment is called intelligent.", "In other words, it can be defined as programming such machines which can think and act with some level of human intelligence is known as artificial intelligence. Artificial intelligence can be defined as efficiently use of limited resources. So artificial intelligence can be defined as making computer programs to solve complex problems same like as human solve the problems. So it is also divided into two parts one is to solving complex problems by the machine and second is same like human beings. The term artificial intelligence is also used to describe a property of machines or programs: the intelligence that the system demonstrates. Artificial intelligence is combination of science and engineering for making the machines which behaves in intelligent manner. In it many fields are combined like philosophy, psychology and computer science."],
                            secImage: "/images/paperImage/image2.jpg",
                            secImageCaption: " Working of a search engine",

                        },
                        {
                            secTitle: "Scope of artificial intelligence in different areas",
                            secContent: [],
                            subSection: [
                                {
                                    subSectionTitle: "In the field of education",
                                    subSectionContent: [],
                                    subSubSection: [{
                                        subsubSectionTitle: "Artificial intelligence can automate basic activities in education, like grading",
                                        subsubSectionContent: ["While AI may not ever be able to truly replace human grading, it’s getting pretty close. It’s now possible for teachers to automate grading for nearly all kinds of multiple choice and fill-in-the-blank testing and automated grading of student writing may not be far behind. Today, essay-grading software is still in its infancy and not quite up to par, yet it in college, grading homework and tests for large lecture courses can be tedious work, even when TAs split it between them. Even in lower grades, teachers often find that grading takes up a significant amount of time, time that could be used to interact with students, prepare for class, or work on professional development."],
                                    },
                                    {
                                        subsubSectionTitle: "Educational software can be adapted to student needs",
                                        subsubSectionContent: ["From kindergarten to graduate school, one of the key ways artificial intelligence will impact education is through the application of greater levels of individualized learning. Some of this is already happening through growing numbers of adaptive learning programs, games, and software. These systems respond to the needs of the student, putting greater emphasis on certain topics, repeating things that students haven’t mastered, and generally helping students to work at their own pace, whatever that may be. This kind of custom tailored education could be a machine-assisted solution to helping students at different levels work together in one classroom, with teachers facilitating the learning and offering help and support when needed.", "Adaptive learning has already had a huge impact on education across the nation (especially through programs like Khan Academy), and as AI advances in the coming decades adaptive programs like these will likely only improve and expand."],
                                    },]
                                },
                                {
                                    subSectionTitle: "Language understanding",
                                    subSectionContent: ["Teachers may not always be aware of gaps in their lectures and educational materials that can leave students confused about certain concepts. Artificial intelligence offers a way to solve that problem. Coursera, a massive open online course provider, is already putting this into practice. When a large number  of students are found to submit the wrong answer to a homework assignment, the system alerts the teacher and gives future students a customized message that offers hints to the correct answer. This type of system helps to fill in the gaps in explanation that can occur in courses, and helps to ensure that all students are building the same conceptual foundation. Rather than waiting to hear back from the professor, students get immediate feedback that helps them to understand a concept and remember how to do it correctly the next time around.", "The ability to 'understand' and respond to the natural language. To translate from spoken language to a written form and to translate from one natural language to another natural language."],
                                    subSectionImage: "/images/paperImage/image3.jpg",
                                    subSectionImageCaption: "Working of a search engine",
                                },]
                        },
                        {
                            secTitle: "Searching techniques in artificial intelligence",
                            secContent: ["In AI for finding the solution of problem searching has to be done because solution is not known in advance. For it AI programs are developed which do the searching process for solution because solution steps are not known before hand and have to be found out. For doing searching following steps are required. So we can say that searching is a process which transform initial state to goal state."],
                        },
                        {
                            secTitle: "Conclusion",
                            secContent: ["The field of artificial intelligence gives the ability to the machines to think analytically, using concepts. Tremendous contribution to the various areas has been made by the Artificial Intelligence techniques from the last 2 decades. Artificial Intelligence will continue to play an increasingly important role in the various fields. This paper is based on the concept of artificial intelligence, scope of artificial intelligence in different areas with special to “the field of education”. As all know artificial intelligence is intelligence behavior of machines which is given by the professional. As you all know artificial intelligence have simplified our life in every aspect it can be article writing or game playing or taking any important decision. In any machine many experts mind can be combined which is more powerful than a single expert mind.", "Many labors work can be done by a single machine and good thing of it is that it never tired. Now such types of robots are going to make which have emotions it will finish the loneliness of the person. But it has another aspect that is can be dangers for us. If we become completely dependent on that machines than it can ruin our life as we do not do any work ourselves and got lazy. And another is that it cannot give the feeling like human. So machines should be used only where there those are actually required."],

                        },
                    ],
                    reference: ["Ramesh N, Kambhampati C, Monson JRT, Drew PJ. Artificial intelligence, 2004.", "Sampada C et al. Adaptive Neuro-Fuzzy Intrusion Detection Systems, Proceedings: International Conference on Information Technology: Coding and Computing ITCC 04, 2004.", "Deepa SN, Aruna Devi B. A survey on intelligence approaches for medical image  Indian Journal of Science and Technology, 2011; 4(11).", "Zadeh L. Fuzzy sets Inf Control, IJET, 2014.", "Joanna Bryson and Jeremy Wyatt. Artificial Intelligence Retrieved from: http://www.cs.bath.ac .uk/~jjb/web/whatisai.html, 1997."]
                }
            },
        ]
    },
]